### ISSUE TITLE
Problem while executing with an empty file.

### ISSUE THREAD

**Issue by kaushal225** [Preetam-Das/typo#1]
while executing the program with empty or uncreated file a runtime error is occuring.

**Comment by preetamsad** [comment]
Assigning this issue to you.
### To do:
- Check if the file exists or not.
- Check for file with empty content.

After completion send a pull request with an appropriate branch name, i will merge it :).

**Comment by SteliosMalamas** [comment]
Issue is fixed in #2 . Sorry for accidentally not making a seperate pull request for that.

**Comment by SteliosMalamas** [comment]
Issue is fixed here: #4
